create table pastry
(
    id    bigint generated by default as identity
        constraint pastry_pkey
            primary key,
    abbr  varchar(50)                not null,
    title text                       not null,
    price double precision default 0 not null
);

alter table pastry
    owner to postgres;

create unique index pastry_abbr_uindex
    on pastry (abbr);

insert into pastry (abbr, title, price) values ('abcr', 'All Butter Croissant', 0.75);
insert into pastry (abbr, title, price) values ('ccr', 'Chocolate Croissant', 0.95);
insert into pastry (abbr, title, price) values ('b', 'Fresh Baguette', 1.60);
insert into pastry (abbr, title, price) values ('rv', 'Red Velvet', 3.95);
insert into pastry (abbr, title, price) values ('vs', 'Victoria Sponge', 5.45);
insert into pastry (abbr, title, price) values ('cc', 'Carrot Cake', 3.45);